#!/usr/bin/env python
""" command of talk through a socket """
import os
import sys
from getopt import getopt,GetoptError
try:
    from talk import Listener,speak,LOG_FORMAT
except ImportError, detail:
    sys.exit('ImportError: %s' % detail) 

def usage():
    command = sys.argv[0]
    sys.stdout.write('Usage: %s <option> <command>\n' % command)    

if __name__ == '__main__':
    """ command execution """
    # handle options
    option = "h"
    long_option = ["help",]
    try:
        opt_list, arg_list = getopt(sys.argv[1:], option, long_option)
    except GetoptError, detail:
        sys.exit('GetoptError: %s' % detail)
    for opt, arg in opt_list:
        if opt in ('-h', '--help'):
            usage()
    # get info 
    addr = '127.0.0.1'
    queue = 'default'
    uid = os.getuid()
    gid = os.getgid()
    cwd = os.getcwd()
    shell = os.environ.get('SHELL')
    # speak
    if len(arg_list) > 0:
        job_message = ' '.join(arg_list[0:])
        message = ('enqueue %s UID %d GID %d CWD %s SHELL %s JOB %s' % (queue,uid,gid,cwd,shell,job_message))
        speak(message, addr=addr)
    else:
        usage()
